import Head from "next/head";
import Image from "next/image";
import { useSession } from "next-auth/react";
import { useRef, useState, useEffect, useContext } from "react";
import styles from "../styles/Home.module.css";
import Dashboard from "./../components/Dashboard";
import AppContext from "../components/AppContext";
import PanelContentWrapper from "../components/PanelContentWrapper";
import Script from "next/script";

export default function Home() {
  const [isPanelOpen, setIsPanelOpen] = useState(false);
  const panelRef = useRef(null);
  const closeBtnRef = useRef(null);
  const context = useContext(AppContext);
  useEffect(() => {
    setIsPanelOpen(context.panelState.isGlobalPanelOpen);

    panelRef.current.style.display = "none";
  }, []);

  useEffect(() => {
    if (context.panelState.isGlobalPanelOpen) {
      panelRef.current.style.display = "block";
      panelRef.current.classList.remove("slide-out-right");
      panelRef.current.classList.add("slide-in-right");
    } else {
      panelRef.current.classList.remove("slide-in-right");
      panelRef.current.classList.add("slide-out-right");
    }
  }, [context.panelState.isGlobalPanelOpen]);

  const handleCloseBtnClick = () => {
    isPanelOpen ? setIsPanelOpen(false) : setIsPanelOpen(true);
    context.setGlobalPanelOpen(isPanelOpen);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Dashboard />
      <div ref={panelRef} className={styles.secretDemoPanel}>
        <div
          ref={closeBtnRef}
          onMouseDown={() => handleCloseBtnClick()}
          className={styles.closeBtnWrapper}
        >
          <img src="/close-panel-icon.png" alt="close panel btn" />
        </div>
        <PanelContentWrapper title={context.panelState.title} />
      </div>
    </div>
  );
}
